DROP TABLE customers;
CREATE TABLE customers(
id INTEGER AUTO_INCREMENT PRIMARY KEY,
   firstname VARCHAR(50) NOT NULL,
   lastname VARCHAR(50) NOT NULL,
   phonenumber VARCHAR(12) NOT NULL
);
DROP TABLE products;
CREATE TABLE products(
id INTEGER AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(100) NOT NULL,
price DECIMAL(2,2) NOT NULL,
description VARCHAR(255)
);

DROP TABLE orders;
CREATE TABLE orders(
customer_id INT NOT NULL,
product_id INT NOT NULL,
created_at TIMESTAMP DEFAULT NOW()
);